module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    screens: {
      xxs: '380px',
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      light: { raw: '(prefers-color-scheme: light)' },
      dark: { raw: '(prefers-color-scheme: dark)' },
    },
    extend: {
      colors: {
        black: 'var(--color-black)',
        paper: 'var(--color-paper)',
        paperDarker: 'var(--color-paperDarker)',
        red: 'var(--color-red)',
        brightRed: 'var(--color-brightRed)',
        blue: 'var(--color-blue)',
        blueLight: 'var(--color-blueLight)',
        bg: 'var(--color-bg)',
        bgTransparent: 'var(--color-bgTransparent)',
        bgDarker: 'var(--color-bgDarker)',
        bgHighlight: 'var(--color-bgHighlight)',
        border: 'var(--color-border)',
        inputBg: 'var(--color-inputBg)',
        inputBorder: 'var(--color-inputBorder)',
        subduedText: 'var(--color-subduedText)',
        buttonBg: 'var(--color-buttonBg)',
      },
    },
  },
  plugins: [],
}
