name: Close Outdated Dependabot PRs

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2am UTC
  workflow_dispatch:      # Allows you to run it manually from the Actions tab

jobs:
  close-old-prs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-pr-labels: 'dependencies'
          stale-pr-message: 'This PR is outdated because a newer update is available.'
          close-pr-message: 'Closing this PR as a newer dependency update is available.'
          days-before-pr-stale: 1
          days-before-pr-close: 1
